#!/bin/bash

# echo command to print the input provided

echo Hello World
echo
echo Hello Murewa

# Print Multiple lines

echo -e "Hello World\nHello Murewa"

# When you are using \n to print new lines, then quote the input, Also enable -e option
